
-- CONTATO CERTO SP - SCHEMA COMPLETO
create extension if not exists "pgcrypto";
create table if not exists cidades_sp (id serial primary key, nome text unique not null, estado text default 'SP');
create table if not exists usuarios (id uuid primary key default gen_random_uuid(), tipo text not null check (tipo in ('CLIENTE','MONTADOR','ADMIN')), nome text not null, email text unique not null, senha_hash text not null, cpf text, telefone text, whatsapp text, cidade text, endereco text, status text default 'ATIVO', created_at timestamp default now());
create table if not exists clientes (id uuid primary key references usuarios(id) on delete cascade, data_nascimento date, cep text, bairro text, numero text, complemento text, ponto_referencia text);
create table if not exists montadores (id uuid primary key references usuarios(id) on delete cascade, foto_url text, cidade_principal text, municipios_atendidos text[], experiencia text, especialidades text[], chave_pix text not null, banco text, titular_pix text, status text default 'PENDENTE' check (status in ('PENDENTE','APROVADO','SUSPENSO','BLOQUEADO')), avaliacao_media numeric default 0, total_servicos int default 0);
create table if not exists servicos (id text primary key, categoria text not null, movel text not null, tipo text, caracteristicas text, servico text not null, preco numeric not null, ativo boolean default true);
create table if not exists pedidos (id uuid primary key default gen_random_uuid(), numero serial unique, cliente_id uuid references usuarios(id), servico_id text references servicos(id), categoria text, movel text, quantidade int default 1, marca text, modelo text, observacoes text, fotos text[], cep text, estado text default 'SP', cidade text not null, bairro text, rua text, numero text, complemento text, ponto_referencia text, data_desejada date, horario_desejado text, valor_bruto numeric not null, comissao numeric not null, valor_liquido numeric not null, status text default 'AGUARDANDO_PAGAMENTO', montador_id uuid references usuarios(id), tempo_aceite_inicio timestamp, created_at timestamp default now(), updated_at timestamp default now());
create table if not exists pagamentos (id uuid primary key default gen_random_uuid(), pedido_id uuid references pedidos(id) on delete cascade, valor numeric not null, chave_pix text default 'contatocerto.prestadores@gmail.com', status text default 'AGUARDANDO', comprovante_url text, admin_responsavel text, data_envio timestamp, data_analise timestamp, data_confirmacao timestamp, observacoes text, created_at timestamp default now());
create table if not exists historico_status (id uuid primary key default gen_random_uuid(), pedido_id uuid references pedidos(id) on delete cascade, status text not null, descricao text, responsavel text, created_at timestamp default now());
create table if not exists repasses (id uuid primary key default gen_random_uuid(), pedido_id uuid references pedidos(id), montador_id uuid references usuarios(id), valor_bruto numeric, comissao numeric, valor_liquido numeric, chave_pix_montador text, status text default 'AGUARDANDO', admin_responsavel text, data_confirmacao timestamp, created_at timestamp default now());
create table if not exists avaliacoes (id uuid primary key default gen_random_uuid(), pedido_id uuid references pedidos(id), cliente_id uuid references usuarios(id), montador_id uuid references usuarios(id), nota_geral int check (nota_geral between 1 and 5), qualidade int, pontualidade int, atendimento int, comentario text, created_at timestamp default now(), unique(pedido_id));
create table if not exists mensagens_contato (id uuid primary key default gen_random_uuid(), nome text, telefone text, email text, assunto text, mensagem text, created_at timestamp default now());
alter table cidades_sp enable row level security; alter table usuarios enable row level security; alter table clientes enable row level security; alter table montadores enable row level security; alter table servicos enable row level security; alter table pedidos enable row level security; alter table pagamentos enable row level security; alter table historico_status enable row level security; alter table repasses enable row level security; alter table avaliacoes enable row level security; alter table mensagens_contato enable row level security;
drop policy if exists "allow all" on cidades_sp; create policy "allow all" on cidades_sp for all using (true) with check (true);
drop policy if exists "allow all" on usuarios; create policy "allow all" on usuarios for all using (true) with check (true);
drop policy if exists "allow all" on clientes; create policy "allow all" on clientes for all using (true) with check (true);
drop policy if exists "allow all" on montadores; create policy "allow all" on montadores for all using (true) with check (true);
drop policy if exists "allow all" on servicos; create policy "allow all" on servicos for all using (true) with check (true);
drop policy if exists "allow all" on pedidos; create policy "allow all" on pedidos for all using (true) with check (true);
drop policy if exists "allow all" on pagamentos; create policy "allow all" on pagamentos for all using (true) with check (true);
drop policy if exists "allow all" on historico_status; create policy "allow all" on historico_status for all using (true) with check (true);
drop policy if exists "allow all" on repasses; create policy "allow all" on repasses for all using (true) with check (true);
drop policy if exists "allow all" on avaliacoes; create policy "allow all" on avaliacoes for all using (true) with check (true);
drop policy if exists "allow all" on mensagens_contato; create policy "allow all" on mensagens_contato for all using (true) with check (true);
insert into usuarios (tipo, nome, email, senha_hash, status) values ('ADMIN','Andre Sousa','andre@contatocertosp.com.br', crypt('Contato@2026SP', gen_salt('bf')), 'ATIVO') on conflict (email) do nothing;
